import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react';
import {api} from './api';
import ExitSettings,{exitOptions,stopOptions,exitReasonLabel} from './ExitSettings';
import TimeframeSettings,{effectiveTimeframe} from './TimeframeSettings';
import type {Page} from './Tabs';
import BacktestChart,{EquityChart} from './BacktestChart';
import {fmt,type BacktestSettings,type BacktestResult,type Trade} from './types';
const utc = (t:number)=>new Date(t*1000).toISOString().replace('T',' ').slice(0,16);
type NumericSetting = {[K in keyof BacktestSettings]: BacktestSettings[K] extends number ? K : never}[keyof BacktestSettings];
const labels: [NumericSetting,string,number,number,number][] = [
  ['capital','Starting account (USDT)',1,1e9,1],['tick_size','Tick size (price units)',.00001,10,.00001],
  ['fee_bps','Fee per side (bps)',0,100,.1],['spread','Full spread (price units)',0,10,.001],
  ['slippage','Slippage per fill (price units)',0,10,.001],['funding_bps','Funding per 8 hours (bps)',-100,100,.1],
  ['max_leverage','Notional / equity cap',1,100,.5],['session_start','Session start hour',0,23,1],['session_end','Session end hour (24 = midnight)',0,24,1]
];
function initial(range:{startDate:string;endDate:string}):BacktestSettings {
  const start = Date.parse(range.startDate), end = Date.parse(range.endDate);
  return {ema_fast:20,ema_slow:50,rsi_period:20,rsi_threshold:50,rsi_active:true,exit_condition:'ema',stop_mode:'none',strategy:'mtf',direction_active:true,direction_timeframe:'1h',setup_active:true,setup_timeframe:'15m',entry_active:true,entry_timeframe:'5m',start_date:range.startDate,end_date:range.endDate,validation_date:new Date(start+Math.max(86400000,Math.floor((end-start)/86400000*.7)*86400000)).toISOString().slice(0,10),capital:2000,tick_size:.01,fee_bps:5,spread:.01,slippage:.01,funding_bps:1,max_leverage:1,session_start:0,session_end:24,session_timezone:'UTC'};
}
export default function BacktestPanel({range,view,onViewChange}:{range:{startDate:string;endDate:string};view:Page;onViewChange:(page:Page)=>void}) {
  const [settings,setSettings]=useState(()=>initial(range));
  const [result,setResult]=useState<BacktestResult|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const [periodKey,setPeriodKey]=useState<'research'|'validation'>('research');
  const [selected,setSelected]=useState<Trade|null>(null),[page,setPage]=useState(0);
  const selectTrade=useCallback((t:Trade)=>setSelected(t),[]);
  async function run(e?:FormEvent) {
    e?.preventDefault();setBusy(true);setError('');
    try {
      const value = await api<BacktestResult>('/api/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});
      setResult(value);setSelected(value[periodKey].trades[0]??null);setPage(0);if(e)onViewChange('results');
    } catch(e) {setError(String(e));} finally {setBusy(false);}
  }
  useEffect(()=>{void run();},[]);
  const period=result?.[periodKey];
  const stale=result && Object.keys(settings).some(k=>settings[k as keyof BacktestSettings]!==result.settings[k as keyof BacktestSettings]);
  const summary=period?.summary;
  const resultTimeframe=result?.executionTimeframe??'5m';
  const exitCounts=useMemo(()=>Object.entries((period?.trades??[]).reduce<Record<string,number>>((counts,t)=>{counts[t.exitReason]=(counts[t.exitReason]??0)+1;return counts;},{})),[period]);
  const pages=period?Math.max(1,Math.ceil(period.trades.length/15)):1;
  const canRun=effectiveTimeframe(settings)!==null && settings.ema_fast<settings.ema_slow;
  const chartIndicators=useMemo(()=>result?.indicators?.filter(c=>period && c.time>=period.start && c.time<period.end)??[],[result,period]);
  const chartCandles=useMemo(()=>result?.candles.filter(c=>period && c.time>=period.start && c.time<period.end)??[],[result,period]);
  function download() {
    if(!result)return;
    const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});
    const url=URL.createObjectURL(blob), a=document.createElement('a');a.href=url;a.download=`silver-${result.settings.strategy}-backtest.json`;a.click();URL.revokeObjectURL(url);
  }
  return <section className="backtest" hidden={view==='price'}>
    <div id="page-strategy" role="tabpanel" aria-labelledby="tab-strategy" hidden={view!=='strategy'}><div className="section-heading"><div><small>STRATEGY CONFIGURATION</small><h2>{settings.strategy==='mtf'?'Multi-timeframe EMA + RSI':'15m structure / 5m sweep'}</h2></div><span className="badge">{settings.strategy==='mtf'?'EMA reversal exit · no stop loss':'Fixed rules · 0.5% risk'}</span></div>
    {settings.strategy==='sweep'&&<p>Rising confirmed highs and lows allow longs; falling highs and lows allow shorts. A sweep reclaims the previous six completed 5m candles’ extreme. Entry is one tick beyond the sweep candle, valid for three candles; stop is one tick beyond its opposite extreme, target is 2R. No replacement strategy is used for ranges.</p>}
    <form onSubmit={run}><fieldset disabled={busy}>
      <label className="strategy-select">Strategy<select aria-label="Strategy" value={settings.strategy} onChange={e=>setSettings({...settings,strategy:e.target.value as BacktestSettings['strategy'],exit_condition:e.target.value==='mtf'?'ema':'none',stop_mode:e.target.value==='mtf'?'none':'fixed'})}><option value="mtf">Multi-timeframe EMA + RSI</option><option value="sweep">Structure / liquidity sweep</option></select></label>
      {settings.strategy==='mtf'&&<TimeframeSettings settings={settings} onChange={setSettings}/>}
      <div className="exit-settings"><h3>Indicator settings</h3><p>Periods apply to all active timeframes and EMA reversal exits.</p><div className="settings-grid">{([['ema_fast','Fast EMA period',1,500],['ema_slow','Slow EMA period',2,1000],['rsi_period','RSI period',1,500],['rsi_threshold','RSI threshold',1,99]] as const).map(([key,label,min,max])=><label key={key}>{label}<input aria-label={label} type="number" min={min} max={max} step={1} required value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div>{settings.strategy==='mtf'&&<label className="stage-switch"><input type="checkbox" role="switch" aria-label="RSI active" checked={settings.rsi_active} onChange={e=>setSettings({...settings,rsi_active:e.target.checked})}/>RSI {settings.rsi_active?'Active':'Disabled'} · Setup and Entry filter</label>}{settings.ema_fast>=settings.ema_slow&&<p role="alert">Fast EMA period must be less than slow EMA period.</p>}<p>Saturday and Sunday are excluded using the session timezone. Positions close before the weekend.</p></div>
      <ExitSettings settings={settings} onChange={setSettings}/>
      <div className="settings-grid">
      {(['start_date','validation_date','end_date'] as const).map((key,i)=><label key={key}>{['Start date (UTC)','Validation starts (UTC)','End date inclusive (UTC)'][i]}<input type="date" required min={range.startDate} max={range.endDate} value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}
      {labels.map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" required min={min} max={max} step={step} value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}
      <label>Session timezone<select value={settings.session_timezone} onChange={e=>setSettings({...settings,session_timezone:e.target.value})}>{['UTC','Asia/Shanghai','America/New_York','Europe/London'].map(t=><option key={t}>{t}</option>)}</select></label>
    </div><div className="form-actions"><span>Available {range.startDate} – {range.endDate} · {settings.strategy==='mtf'?'No daily trade or loss-count limit':'max 2 trades / session · stop after 2 losses'}</span><button type="submit" disabled={!canRun}>{busy?'Backtesting…':'Run backtest'}</button></div></fieldset></form>
    <p className="notice">Tick size and costs are editable assumptions, not verified exchange specifications. Defaults: 0.01 tick, 5 bps fee per side, 0.01 full spread, 0.01 slippage per fill, +1 bp funding at 00/08/16 UTC. Positive funding charges longs and credits shorts. These candles contain no historical funding, spread, or order-book data.</p>
    <details><summary>Execution and validation rules</summary>{settings.strategy==='mtf'?<p>EMAs use SMA seeds and RSI uses Wilder smoothing. Indicators restart after data gaps, and warmup depends on the configured periods. Fresh execution-timeframe alignment plus every active confirmation submits a market order for the next candle’s open. No stop loss or profit target is placed. Fast/slow EMA reversal closes at the next open. The signal candle’s low/high remains a position-sizing reference only; it does not limit losses. No swing/resistance filter applies to this strategy.</p>:<p>Strict swings require two lower highs or higher lows on each side and are usable only after the second following 15m candle closes. Resistance/support uses all previously confirmed 15m swings still unbroken by a 15m close. Skip if the nearest level offers less than 2R; recheck on gap fills.</p>}<p>{settings.strategy==='mtf'?'Multiple concurrent positions are allowed; each fresh qualifying signal can add a trade within the total notional cap.':'One position or pending order at a time.'} Only execution candles fully inside the selected session are tradable. {settings.strategy==='sweep'?'Sweep orders are valid for the next three 5m bars.':'EMA + RSI orders enter at the next execution candle’s open.'} Stops win when intrabar ordering is unknown. Spread/2 + slippage is adverse on every fill, including targets. Fees apply on both sides. Funding is a fixed scenario at UTC 00/08/16 for positions already open. Positions close and pending orders cancel at session or period end; missing data forces a last-known-close exit.</p><p>The sizing reference is 0.5% of current equity including estimated execution and fees; EMA + RSI has no stop and this is not a loss limit; a notional cap can reduce actual risk. Gaps and funding can exceed planned risk. Quantity is continuous silver-equivalent units, without contract lot rounding or liquidation simulation. Shaded zones show gross 2R geometry; net reward is lower after costs.</p><p>Research and validation use identical settings and each starts with the selected account balance. Earlier candles warm up swing structure; no position crosses the split. The initial split reserves the final 30% of calendar history. Validation is a later-period check, not proof of profitability or a fresh holdout after repeated tuning. Exit timestamps identify the containing execution candle, not an exact intrabar fill.</p>{settings.strategy==='sweep'&&<p>Previous highs/lows as support and resistance: <a href="https://www.cmegroup.com/education/courses/trading-and-analysis/support-and-resistance.html" target="_blank" rel="noreferrer">CME reference</a>. Candle sweeps do not establish actual order clusters.</p>}</details>
    </div>
    {error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Simulating completed candles and trading costs…</p>}{stale&&<p className="notice">Settings changed. Results still use the last run; run backtest to update.</p>}
    {result&&period&&summary&&<><div hidden={view==='strategy'}><div className="section-heading period-tabs"><div>{(['research','validation'] as const).map(key=><button key={key} type="button" disabled={busy} className={periodKey===key?'active':'secondary'} onClick={()=>{setPeriodKey(key);setSelected(result[key].trades[0]??null);setPage(0);}}>{key==='research'?'Research':'Validation'} · {result[key].summary.trades} trades</button>)}</div><button className="secondary" onClick={download}>Export result JSON</button></div>
      <p>{period.name}: {utc(period.start)} → {utc(period.end)} UTC (end exclusive). Account resets to {fmt(result.settings.capital)} USDT. Session {result.settings.session_start}:00–{result.settings.session_end}:00 {result.settings.session_timezone}. Strategy: {result.strategyName??'Structure / liquidity sweep'} · execution: {resultTimeframe.toUpperCase()}, independent of the price chart selector. Close: {exitOptions[result.settings.exit_condition??'none']} · stop: {stopOptions[result.settings.stop_mode??'fixed']}.</p>
      </div><div id="page-results" role="tabpanel" aria-labelledby="tab-results" hidden={view!=='results'}>
      <h2>Results & account equity</h2><div className="metrics">{[['Net return',`${fmt(summary.returnPct)}%`],['Ending equity',`${fmt(summary.endingBalance)} USDT`],['Closed trades',String(summary.trades)],['Win rate',`${fmt(summary.winRate)}%`],['Max drawdown',`${fmt(summary.maxDrawdownPct)}%`],['Profit factor',summary.profitFactor===null?'N/A':fmt(summary.profitFactor)],['Average net R',fmt(summary.averageR)],['Fees',`${fmt(summary.fees)} USDT`],['Funding paid / credit',`${fmt(summary.funding)} USDT`],['Spread + slippage',`${fmt(summary.executionCost)} USDT`]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>
      <p className={summary.meets100Trades?'caption':'notice'}>{summary.meets100Trades?'100-trade sample reached.':`Only ${summary.trades} / 100 trades. This period does not meet the requested sample size.`} {summary.wins} wins, {summary.losses} losses; net P&amp;L {fmt(summary.netPnl)} USDT. {period.status==='no_complete_bars'?'No complete bars within this period.':''}</p>
      <p>{period.diagnostics.signals??period.diagnostics.sweeps} {result.settings.strategy==='mtf'?'confirmed signals':'sweep setups'} · {period.diagnostics.blockedByLevel} blocked by nearby levels · {period.diagnostics.invalidEntries??0} invalid gap entries · {period.diagnostics.expiredOrders} expired orders · {period.diagnostics.cancelledOrders} cancelled orders · {period.diagnostics.ambiguousBars} conservative intrabar exits.</p>
      <div className="exit-breakdown" aria-label="Exit breakdown">{exitCounts.map(([reason,count])=><span key={reason}>{exitReasonLabel(reason)}: <b>{count}</b></span>)}</div>
      <h3>Equity after costs</h3><EquityChart period={period}/>
      </div><div id="page-positions" role="tabpanel" aria-labelledby="tab-positions" hidden={view!=='positions'}>
      <div className="section-heading"><h3>Trading positions · {resultTimeframe.toUpperCase()}</h3><button className="secondary" onClick={()=>setSelected(null)}>Latest candles / all markers</button></div>
      <p>Green arrows: buys · rose arrows: sells · circles: exits. Select a trade to focus its signal, blue entry line, red initial-risk zone, moving stop line, and green target zone. Drag or zoom to explore the full selected period, including candles before and after the selected trade.</p>
      <BacktestChart indicators={chartIndicators} indicatorSettings={result.settings} barSeconds={result.barSeconds??300} timeframe={resultTimeframe} candles={chartCandles} trades={period.trades} selected={selected} onSelect={selectTrade}/>
      {selected&&<div className="trade-detail"><h3>#{selected.id} {selected.direction===1?'Long':'Short'} · {exitReasonLabel(selected.exitReason)}</h3><p>{selected.signalLabel??'Sweep'} candle {utc(selected.signalTime)} · entry {utc(selected.entryTime)} · exit {utc(selected.exitTime)} UTC. Entry {fmt(selected.entry,3)} → exit {fmt(selected.exit,3)} · {selected.stop===null?'No stop loss or profit target':`initial stop ${fmt(selected.stop,3)} → final stop ${fmt(selected.finalStop??selected.stop,3)} · target ${fmt(selected.target,3)}`}  · quantity {fmt(selected.quantity,4)}.</p><p>Sizing reference {fmt(selected.riskBudget)} / planned stop loss {fmt(selected.plannedRisk)} USDT · net P&amp;L {fmt(selected.netPnl)} USDT ({fmt(selected.netR)} R). {!selected.confirmations&&<>Confirmed highs {selected.swingHighs.map(v=>fmt(v,3)).join(' → ')}; lows {selected.swingLows.map(v=>fmt(v,3)).join(' → ')}.</>} {selected.ambiguous?'Intrabar sequence was ambiguous; conservative stop assumed.':''}</p>{selected.exitSignal&&<p className="exit-signal-detail">Close signal: {exitReasonLabel(selected.exitSignal.reason)} confirmed {utc(selected.exitSignal.closeTime)} UTC · EMA{result.settings.ema_fast} {selected.exitSignal.ema20===null?'—':fmt(selected.exitSignal.ema20,3)} · EMA{result.settings.ema_slow} {selected.exitSignal.ema50===null?'—':fmt(selected.exitSignal.ema50,3)} · RSI{result.settings.rsi_period} {selected.exitSignal.rsi20===null?'—':fmt(selected.exitSignal.rsi20)}.</p>}{(selected.stopHistory?.length??0)>1&&<details className="stop-history"><summary>Stop adjustments ({selected.stopHistory!.length-1})</summary><table><thead><tr><th>Effective (UTC)</th><th>Stop</th><th>Rule</th></tr></thead><tbody>{selected.stopHistory!.map(h=><tr key={h.time}><td>{utc(h.time)}</td><td>{fmt(h.price,3)}</td><td>{h.reason}</td></tr>)}</tbody></table></details>}{selected.confirmations&&<div className="table-scroll"><table aria-label="Entry confirmations"><thead><tr><th>Active stage</th><th>Timeframe</th><th>Confirmed close (UTC)</th><th>EMA {result.settings.ema_fast}</th><th>EMA {result.settings.ema_slow}</th><th>RSI {result.settings.rsi_period}</th></tr></thead><tbody>{selected.confirmations.map(c=><tr key={c.stage}><th>{c.stage}</th><td>{c.timeframe.toUpperCase()}</td><td>{utc(c.closeTime)}</td><td>{fmt(c.ema20,3)}</td><td>{fmt(c.ema50,3)}</td><td>{c.rsi20===null?'Not used':fmt(c.rsi20)}</td></tr>)}</tbody></table></div>}</div>}
      <h3>Trade ledger · select a row to show its position</h3><div className="table-scroll"><table><thead><tr>{['Trade','Entry UTC','Side','Entry','Stop','Target','Exit','Net P&L','Net R','Exit reason'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{period.trades.slice(page*15,page*15+15).map(t=><tr key={t.id} onClick={()=>selectTrade(t)} className={selected?.id===t.id?'selected-row':''}><td><button className="trade-link" onClick={()=>selectTrade(t)}>#{t.id}</button></td><td>{utc(t.entryTime)}</td><td>{t.direction===1?'Long':'Short'}</td>{[t.entry,t.stop,t.target,t.exit].map((v,i)=><td key={i}>{fmt(v,3)}</td>)}<td className={t.netPnl>=0?'positive':'negative'}>{fmt(t.netPnl)}</td><td>{fmt(t.netR)}</td><td>{exitReasonLabel(t.exitReason)}</td></tr>)}</tbody></table></div>
      {!period.trades.length&&<p>No trades met all rules in this period.</p>}<div className="pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} / {pages}</span><button className="secondary" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next</button></div>
    </div></>}
  </section>;
}
