import type {BacktestSettings} from './types';
import {effectiveTimeframe} from './TimeframeSettings';
export const exitOptions = {none:'Stop / target only',ema:'Fast / slow EMA reversal',rsi:'RSI crosses against the trade through its threshold',either:'EMA reversal OR RSI cross'};
export const stopOptions = {none:'Disabled',fixed:'Fixed initial stop',breakeven:'Breakeven after +1R',trailing:'Trail completed candle lows / highs',breakeven_trailing:'Breakeven + trailing'};
export const exitReasonLabel=(reason:string)=>({stop:'Stop loss',target:'2R target',ema_exit:'EMA reversal',rsi_exit:'RSI cross',ema_rsi_exit:'EMA + RSI reversal',session_end:'Session end',period_end:'Period end',data_gap:'Data gap'}[reason]??reason.replaceAll('_',' '));
export default function ExitSettings({settings,onChange}:{settings:BacktestSettings;onChange:(s:BacktestSettings)=>void}) {
  const tf=effectiveTimeframe(settings)?.toUpperCase()??'—';
  if(settings.strategy==='mtf') return <div className="exit-settings"><h3>Close condition: EMA {settings.ema_fast} / EMA {settings.ema_slow} reversal</h3><p>{settings.atr_active?'ATR stop loss and EMA reversal work together.':'ATR stop loss is disabled.'} No profit target is placed. A long closes when the fast EMA crosses below the slow EMA; a short closes when the fast EMA crosses above the slow EMA. The signal uses a completed {tf} candle and fills at the next open. Session, period and data-gap exits still apply.</p><label className="stage-switch"><input type="checkbox" role="switch" aria-label="ATR active" checked={settings.atr_active} onChange={e=>onChange({...settings,atr_active:e.target.checked})}/>ATR {settings.atr_active?'Active':'Disabled'}</label><div className="settings-grid"><label>ATR period<input aria-label="ATR period" type="number" min={1} max={500} step={1} required disabled={!settings.atr_active} value={settings.atr_period} onChange={e=>onChange({...settings,atr_period:Number(e.target.value)})}/></label><label>ATR multiplier<input aria-label="ATR multiplier" type="number" min={0.01} max={100} step={0.01} required disabled={!settings.atr_active} value={settings.atr_multiplier} onChange={e=>onChange({...settings,atr_multiplier:Number(e.target.value)})}/></label></div><p>Fixed stop: entry minus ATR × multiplier for longs; plus for shorts. ATR uses the completed {tf} signal candle. Each position keeps its own stop. The stop is active from entry; an EMA reversal exits at the next open if the position is still open.</p></div>;
  return <div className="exit-settings"><div className="section-heading"><h3>Close conditions & stop loss</h3><small>Available for both strategies · execution timeframe {tf}</small></div>
    <div className="settings-grid"><label>Close position when<select aria-label="Close condition" value={settings.exit_condition} onChange={e=>onChange({...settings,exit_condition:e.target.value as BacktestSettings['exit_condition']})}>{Object.entries(exitOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label>Stop management<select aria-label="Stop management" value={settings.stop_mode} onChange={e=>onChange({...settings,stop_mode:e.target.value as BacktestSettings['stop_mode']})}>{Object.entries(stopOptions).filter(([value])=>value!=='none').map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
    <p>Long exit: the fast EMA crosses below the slow EMA, or RSI {settings.rsi_period} crosses below {settings.rsi_threshold}. Short exit: the reverse. Selected conditions are checked on completed {tf} candles; the close order fills at the next open. Existing stops, the 2R target, and session exits remain active.</p>
    <p>Breakeven moves the stop to entry after price reaches +1R. Trailing uses one tick below the last completed candle’s low for longs, or above its high for shorts. Combined mode takes the tighter stop. Stops never loosen, and changes start on the next candle. R always uses the original entry-to-stop distance. Breakeven is before fees, slippage and funding.</p>
  </div>;
}
